/* eslint-disable @next/next/next-script-for-ga */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavFootWrapper from "@/components/layout/navfoot-wrapper";
import { ReactChildren } from "@/lib/types";
import ContextWrapper from "@/lib/contexts/context-wrapper";
import PageView from "./_utils/datalayers/page-view";
// import Head from "next/head";
import type { Viewport } from 'next'
 
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

// Declare the dataLayer object as a global variable
declare global {
  interface Window {
    dataLayer: any[];
  }
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deinhandymarkt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ReactChildren) {
  return (
    <html lang="en">
      {/* <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        ></meta>
      </Head> */}
      <head>
        <script
          id="gtm-script"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-WBXPQRBB');
          `,
          }}
        />
        <script
          id="data-layer"
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];`,
          }}
        />
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-WBXPQRBB"
            height="0"
            width="0"
            style={{ display: "none", opacity: "none" }}
          ></iframe>
        </noscript>
        <PageView />
        <ContextWrapper>
          <NavFootWrapper>
            <main>{children}</main>
          </NavFootWrapper>
        </ContextWrapper>
      </body>
    </html>
  );
}
